import test from 'node:test';
import assert from 'node:assert/strict';
import { createComputeDispatch } from '../src/infrastructure/ecu/compute-dispatch.js';

function job(overrides = {}) {
  return { id:'job-1', runFingerprint:'f'.repeat(64), artifactUri:'r2://ecu-artifacts/originals/abc', artifactSha256:'a'.repeat(64), operation:'analyze', modelVersion:'baseline', rulepackVersion:'baseline', ...overrides };
}

test('prefers an available local worker over cloud compute', async () => { const calls=[]; const dispatch=createComputeDispatch({fetchImpl:async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}}); const result=await dispatch(job(),{ECU_LOCAL_WORKER_URL:'https://local-worker.example/jobs',ECU_LOCAL_WORKER_ONLINE:'1',ECU_CLOUD_WORKER_URL:'https://cloud-worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'}); assert.equal(result.accepted,true);assert.equal(result.workerKind,'local');assert.equal(calls.length,1);assert.equal(calls[0].url,'https://local-worker.example/jobs');assert.equal(calls[0].init.headers['idempotency-key'],'f'.repeat(64)); });

test('falls back to cloud worker when local worker is unavailable', async () => { const calls=[];const dispatch=createComputeDispatch({fetchImpl:async(url)=>{calls.push(url);return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}});const result=await dispatch(job(),{ECU_LOCAL_WORKER_URL:'https://local-worker.example/jobs',ECU_LOCAL_WORKER_ONLINE:'0',ECU_CLOUD_WORKER_URL:'https://cloud-worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(result.workerKind,'cloud');assert.deepEqual(calls,['https://cloud-worker.example/jobs']); });

test('falls back to cloud after a heartbeating local worker cannot accept the job', async () => { const calls=[];const now=3_000_000;const db={prepare(){return {async first(){return {endpoint:'https://stale-local.example/jobs',last_seen_at:now-1000,expires_at:now+60_000};}}}};const dispatch=createComputeDispatch({now:()=>now,fetchImpl:async(url)=>{calls.push(url);if(String(url).includes('stale-local'))throw new Error('tunnel offline');return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}});const result=await dispatch(job(),{DB:db,ECU_CLOUD_WORKER_URL:'https://cloud-worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(result.workerKind,'cloud');assert.deepEqual(calls,['https://stale-local.example/jobs','https://cloud-worker.example/jobs']);assert.equal(result.fallbackFrom,'local'); });

test('temporarily cools down a failed local worker so following jobs go straight to cloud', async () => { const calls=[];let clock=4_000_000;const db={prepare(){return {async first(){return {endpoint:'https://dead-local.example/jobs',last_seen_at:clock-1000,expires_at:clock+60_000};}}}};const dispatch=createComputeDispatch({now:()=>clock,localCooldownMs:30_000,fetchImpl:async(url)=>{calls.push(url);if(String(url).includes('dead-local'))throw new Error('tunnel offline');return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}});const env={DB:db,ECU_CLOUD_WORKER_URL:'https://cloud-worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'};const first=await dispatch(job({id:'job-a',runFingerprint:'a'.repeat(64)}),env);const second=await dispatch(job({id:'job-b',runFingerprint:'b'.repeat(64)}),env);assert.equal(first.workerKind,'cloud');assert.equal(second.workerKind,'cloud');assert.deepEqual(calls,['https://dead-local.example/jobs','https://cloud-worker.example/jobs','https://cloud-worker.example/jobs']);clock+=30_001;await dispatch(job({id:'job-c',runFingerprint:'c'.repeat(64)}),env);assert.equal(calls[3],'https://dead-local.example/jobs'); });

test('reports local cooldown routing without exposing worker endpoint', async () => { const calls=[];let clock=5_000_000;const db={prepare(){return {async first(){return {endpoint:'https://private-laptop-tunnel.example/jobs',last_seen_at:clock-1000,expires_at:clock+60_000};}}}};const dispatch=createComputeDispatch({now:()=>clock,localCooldownMs:30_000,fetchImpl:async(url)=>{calls.push(url);if(String(url).includes('private-laptop'))throw new Error('offline');return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}});const env={DB:db,ECU_CLOUD_WORKER_URL:'https://cloud-worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'};await dispatch(job({id:'job-a',runFingerprint:'a'.repeat(64)}),env);const result=await dispatch(job({id:'job-b',runFingerprint:'b'.repeat(64)}),env);assert.equal(result.workerKind,'cloud');assert.equal(result.routeReason,'LOCAL_COOLDOWN');assert.equal(result.localCooldownRemainingMs,30_000);assert.equal(JSON.stringify(result).includes('private-laptop-tunnel'),false); });

test('exposes safe routing health before dispatch without leaking local endpoint', async () => { let clock=5_500_000;const db={prepare(){return {async first(){return {endpoint:'https://secret-laptop-tunnel.example/jobs',last_seen_at:clock-1000,expires_at:clock+60_000};}}}};const dispatch=createComputeDispatch({now:()=>clock,localCooldownMs:30_000,fetchImpl:async(url)=>{if(String(url).includes('secret-laptop'))throw new Error('offline');return new Response('{}',{status:202});}});const env={DB:db,ECU_CLOUD_WORKER_URL:'https://cloud.example/jobs',ECU_COMPUTE_TOKEN:'secret'};let status=await dispatch.getRoutingStatus(env);assert.equal(status.local.state,'healthy');assert.equal(status.preferredWorkerKind,'local');assert.equal(JSON.stringify(status).includes('secret-laptop-tunnel'),false);await dispatch(job(),env);status=await dispatch.getRoutingStatus(env);assert.equal(status.local.state,'cooldown');assert.equal(status.local.cooldownRemainingMs,30_000);assert.equal(status.preferredWorkerKind,'cloud');clock+=30_001;status=await dispatch.getRoutingStatus(env);assert.equal(status.local.state,'healthy');assert.equal(status.preferredWorkerKind,'local'); });

test('keeps the job recoverable when no worker is configured or dispatch fails', async () => { const noEndpoint=createComputeDispatch({fetchImpl:async()=>{throw new Error('should not run');}});assert.deepEqual(await noEndpoint(job(),{}),{accepted:false,state:'QUEUED',workerKind:null,reason:'NO_COMPUTE_ENDPOINT'});const broken=createComputeDispatch({fetchImpl:async()=>{throw new Error('offline');}});const result=await broken(job(),{ECU_CLOUD_WORKER_URL:'https://cloud-worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,false);assert.equal(result.state,'QUEUED');assert.equal(result.workerKind,'cloud');assert.equal(result.reason,'DISPATCH_FAILED'); });

test('dispatches ORI MOD pair jobs with both immutable artifact hashes', async () => { const calls=[];const dispatch=createComputeDispatch({fetchImpl:async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}});const pair={id:'pair-1',runFingerprint:'p'.repeat(64),operation:'diff_pair',oriArtifactSha256:'a'.repeat(64),modArtifactSha256:'b'.repeat(64),oriArtifactUri:'r2://ecu-artifacts/originals/'+'a'.repeat(64),modArtifactUri:'r2://ecu-artifacts/originals/'+'b'.repeat(64),operationLabel:'stage1',config:{callback_base_url:'https://jarvis.example'}};const result=await dispatch(pair,{ECU_CLOUD_WORKER_URL:'https://worker.example/jobs',ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(calls[0].body.operation,'diff_pair');assert.equal(calls[0].body.ori_artifact_sha256,'a'.repeat(64));assert.equal(calls[0].body.mod_artifact_sha256,'b'.repeat(64));assert.equal(calls[0].body.operation_label,'stage1'); });

test('uses scale-to-zero Cloudflare container binding when local worker is offline', async () => { const calls=[];const stub={async fetch(request){calls.push(request);return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}};const dispatch=createComputeDispatch({fetchImpl:async()=>{throw new Error('external fetch should not run');}});const result=await dispatch(job(),{ECU_LOCAL_WORKER_ONLINE:'0',ECU_COMPUTE_CONTAINER:{getByName(name){assert.equal(name,'jarvis-ecu-compute');return stub;}},ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(result.workerKind,'cloud-container');assert.equal(calls.length,1);assert.equal(new URL(calls[0].url).pathname,'/jobs');assert.equal(calls[0].headers.get('authorization'),'Bearer secret'); });

test('prefers local worker over Cloudflare container binding', async () => { let containerCalls=0;const dispatch=createComputeDispatch({fetchImpl:async()=>new Response(JSON.stringify({accepted:true}),{status:202})});const result=await dispatch(job(),{ECU_LOCAL_WORKER_URL:'https://local.example/jobs',ECU_LOCAL_WORKER_ONLINE:'1',ECU_COMPUTE_CONTAINER:{getByName(){containerCalls++;return {fetch(){}};}},ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.workerKind,'local');assert.equal(containerCalls,0); });

test('does not wake cloud container without compute token', async () => { let woke=false;const dispatch=createComputeDispatch({fetchImpl:async()=>{throw new Error('should not fetch');}});const result=await dispatch(job(),{ECU_COMPUTE_CONTAINER:{getByName(){woke=true;return {fetch:async()=>new Response('{}',{status:202})};}}});assert.equal(result.accepted,false);assert.equal(result.state,'QUEUED');assert.equal(result.reason,'NO_COMPUTE_TOKEN');assert.equal(woke,false); });

test('dispatches training jobs through scale-to-zero container', async () => { const calls=[];const stub={async fetch(request){calls.push(JSON.parse(await request.text()));return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}};const dispatch=createComputeDispatch({fetchImpl:async()=>{throw new Error('external fetch should not run');}});const result=await dispatch({id:'training-1',operation:'train',runFingerprint:'t'.repeat(64),datasetVersion:'dataset-1',datasetDigest:'d'.repeat(64),productionModelVersion:'model-1',config:{callback_base_url:'https://jarvis.example'}},{ECU_COMPUTE_CONTAINER:{getByName(){return stub;}},ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(result.workerKind,'cloud-container');assert.equal(calls.length,1);assert.equal(calls[0].operation,'train');assert.equal(calls[0].dataset_version,'dataset-1');assert.equal(calls[0].dataset_digest,'d'.repeat(64));assert.equal(calls[0].production_model_version,'model-1');assert.equal(calls[0].paid_api_allowed,false); });

test('prefers a recently heartbeating local worker from D1 over cloud container', async () => { const calls=[];const now=1_000_000;const db={prepare(sql){assert.match(sql,/ecu_workers/);return {bind(){return this;},async first(){return {endpoint:'https://laptop-tunnel.example/jobs',last_seen_at:now-10_000,expires_at:now+60_000};}};}};const dispatch=createComputeDispatch({now:()=>now,fetchImpl:async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({accepted:true}),{status:202,headers:{'content-type':'application/json'}});}});const result=await dispatch(job(),{DB:db,ECU_COMPUTE_CONTAINER:{getByName(){throw new Error('cloud must not wake');}},ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(result.workerKind,'local');assert.equal(calls[0].url,'https://laptop-tunnel.example/jobs'); });

test('ignores expired local worker heartbeat and falls back to cloud container', async () => { const now=2_000_000;let cloudCalls=0;const db={prepare(){return {bind(){return this;},async first(){return {endpoint:'https://old.example/jobs',last_seen_at:1,expires_at:now-1};}};}};const dispatch=createComputeDispatch({now:()=>now,fetchImpl:async()=>{throw new Error('external fetch must not run');}});const result=await dispatch(job(),{DB:db,ECU_COMPUTE_CONTAINER:{getByName(){return {async fetch(){cloudCalls++;return new Response('{}',{status:202});}};}},ECU_COMPUTE_TOKEN:'secret'});assert.equal(result.accepted,true);assert.equal(result.workerKind,'cloud-container');assert.equal(cloudCalls,1); });
