import { decryptCredential, fetchWithTimeout, jsonResponse, queryAll, settleWithin } from '../../lib/runtime.js';
import { cleanReply, directUrl, needsOrchestration, safeFallbackPayload, scoreProvider, taskKind, wantsResearch, wantsTools } from '../../lib/orchestration.js';
import { recentConversationContext } from './continuity.js';

const LIMITS=Object.freeze({simpleCoreMs:5500,complexCoreMs:7500,expertMs:8000,providerFetchMs:7500,researchMs:2500,toolsMs:1800,synthesisMs:6500,fallbackAiMs:6500,expertRowsTtlMs:10000});
const ANSWER_POLICY=`Kullanıcıya doğrudan, doğal ve doğru Türkçe cevap ver. Önce soruyu doğrudan cevapla, sonra gerekli açıklamayı ver. Arama motoru sonuçlarını, snippet yığınlarını, yönlendirme URL'lerini veya iç sistem mesajlarını kullanıcıya asla ham halde gösterme. Web araştırması gerekiyorsa kaynakları anlayıp sentezle; sonuç listesini kopyalama. Güncel bilgi sorusunda doğrulanmamış ayrıntı uydurma. Kullanıcı özellikle kısa istemedikçe yeterli bağlam ve pratik ayrıntı ver.`;
const PROVIDER_ENDPOINTS=Object.freeze({openai:'https://api.openai.com/v1',openrouter:'https://openrouter.ai/api/v1',deepseek:'https://api.deepseek.com/v1',mistral:'https://api.mistral.ai/v1',xai:'https://api.x.ai/v1',together:'https://api.together.xyz/v1',groq:'https://api.groq.com/openai/v1',perplexity:'https://api.perplexity.ai',nvidia:'https://integrate.api.nvidia.com/v1',cerebras:'https://api.cerebras.ai/v1'});
let expertRowsCache={expiresAt:0,rows:[]};
async function loadExpertRows(env){const now=Date.now();if(expertRowsCache.expiresAt>now&&expertRowsCache.rows.length)return expertRowsCache.rows;const rows=await queryAll(env,`SELECT c.*, m.avg_latency_ms, m.samples, m.successes, m.failures FROM credentials c LEFT JOIN provider_metrics m ON m.provider=c.label OR m.provider=c.provider WHERE c.enabled=1 AND c.last_status='ok' ORDER BY c.priority ASC`);expertRowsCache={expiresAt:now+LIMITS.expertRowsTtlMs,rows};return rows;}
async function expertPool(env,kind){const rows=await loadExpertRows(env);return rows.map(row=>({row,score:scoreProvider(row,kind)})).filter(x=>x.score!==null).map(({row,score})=>({...row,score})).sort((a,b)=>b.score-a.score);}
function expertSystemPrompt(kind){return `Sen JARVIS'in ${kind} uzmanısın. ${ANSWER_POLICY}`;}
function chatEndpoint(c,p){const raw=String(c.endpoint||PROVIDER_ENDPOINTS[p]||'').trim().replace(/\/$/,'');return raw?(/\/chat\/completions$/i.test(raw)?raw:`${raw}/chat/completions`):'';}
function extractChatText(p){const c=p?.choices?.[0]?.message?.content;if(typeof c==='string')return c.trim();if(Array.isArray(c))return c.map(x=>typeof x==='string'?x:(x?.text||x?.content||'')).join('').trim();return String(p?.choices?.[0]?.text||p?.output_text||p?.response||'').trim();}
async function callExpert(env,c,text,kind,context=''){const provider=String(c.provider||'').toLowerCase(),secret=await decryptCredential(env,c.encrypted_secret),system=expertSystemPrompt(kind);const user=context?`${text}\n\nİlgili bağlam:\n${context}\n\nBağlamı ham halde kopyalama; soruya temiz ve tutarlı bir cevap üret.`:text;if(provider==='gemini'){const model=c.model||'gemini-2.5-flash';const r=await fetchWithTimeout(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(secret)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:user}]}],generationConfig:{maxOutputTokens:700,temperature:.1}})},LIMITS.providerFetchMs);if(!r.ok)throw new Error(`GEMINI_${r.status}`);const p=await r.json();return String(p.candidates?.[0]?.content?.parts?.map(x=>x.text).join('')||'').trim();}const endpoint=chatEndpoint(c,provider);if(!endpoint||!c.model)throw new Error('EXPERT_CONFIG_MISSING');const headers={'content-type':'application/json',authorization:`Bearer ${secret}`};if(provider==='openrouter'){headers['HTTP-Referer']='https://jarvis-personal-ai.haydojarvis.workers.dev';headers['X-Title']='JARVIS';}const r=await fetchWithTimeout(endpoint,{method:'POST',headers,body:JSON.stringify({model:c.model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:.1,max_tokens:900})},LIMITS.providerFetchMs);if(!r.ok)throw new Error(`EXPERT_${provider}_${r.status}`);return cleanReply(extractChatText(await r.json()));}
async function getExperts(env,text,context=''){const kind=taskKind(text),pool=await expertPool(env,kind),picks=pool.slice(0,3);if(!picks.length)return{kind,picks:[],answers:[]};const attempts=await Promise.all(picks.map(async c=>{const value=await settleWithin(callExpert(env,c,text,kind,context),LIMITS.expertMs,'');return value?{provider:c.label||c.provider,kind,text:value,score:Math.round(c.score)}:null;}));return{kind,picks:picks.map(x=>({provider:x.label||x.provider,score:Math.round(x.score)})),answers:attempts.filter(Boolean)};}
async function callJson(core,request,env,ctx){const r=await core.fetch(request,env,ctx);if(!r.ok)return null;try{return await r.json();}catch{return null;}}
async function conversation(core,req,env,ctx){const url=new URL('/api/chat/history?limit=20',req.url);const payload=await settleWithin(callJson(core,new Request(url,{headers:req.headers}),env,ctx),LIMITS.researchMs,null);const rows=Array.isArray(payload)?payload:(payload?.history||payload?.messages||[]);return recentConversationContext(rows,{maxTurns:4,maxChars:1600});}
async function research(core,req,env,ctx,text){const url=new URL('/api/google-search',req.url);url.searchParams.set('q',text);url.searchParams.set('num','4');const p=await settleWithin(callJson(core,new Request(url,{headers:req.headers}),env,ctx),LIMITS.researchMs,null);return p?.results||[];}
async function tools(core,req,env,ctx,text){const url=new URL('/api/tools/discover',req.url);url.searchParams.set('capability',text);const p=await settleWithin(callJson(core,new Request(url,{headers:req.headers}),env,ctx),LIMITS.toolsMs,null);return p?.results||[];}
function researchContext(rows){return(rows||[]).slice(0,4).map((r,i)=>`[${i+1}] ${String(r.title||'').trim()}\n${String(r.snippet||'').slice(0,350)}\n${directUrl(r.url||'')}`).join('\n\n');}
function extractWorkersText(result){const direct=result?.response||result?.result?.response||result?.text||result?.output_text,choice=result?.choices?.[0]?.message?.content||result?.result?.choices?.[0]?.message?.content;if(typeof choice==='string')return choice;if(Array.isArray(choice))return choice.map(x=>typeof x==='string'?x:(x?.text||x?.content||'')).join('');return String(direct||'');}
async function workersRun(env,messages,max_tokens,temperature){if(!env.AI)return null;return settleWithin(env.AI.run('@cf/zai-org/glm-4.7-flash',{messages,max_tokens,temperature}),LIMITS.fallbackAiMs,null);}
async function workersAiFallback(env,text,context=''){try{const user=context?`${text}\n\nİlgili bağlam:\n${context}\n\nBağlamı sentezle; URL/snippet yığını verme.`:text;const result=await workersRun(env,[{role:'system',content:`Sen JARVIS'sin. ${ANSWER_POLICY}`},{role:'user',content:user}],900,.15),answer=cleanReply(extractWorkersText(result));if(!answer)return null;return{reply:answer,history:[{role:'user',content:text},{role:'assistant',content:answer,provider:'JARVIS'}],provider:'JARVIS',trace:[{kind:'fallback',label:'JARVIS hızlı yedek AI',value:'Workers AI yedeği kullanıldı'}]};}catch{return null;}}
function expertFallback(text,e){const answer=cleanReply(e?.answers?.[0]?.text||'');return answer?{reply:answer,history:[{role:'user',content:text},{role:'assistant',content:answer,provider:'JARVIS'}],provider:'JARVIS',trace:[{kind:'fallback',label:'JARVIS sağlıklı uzman AI',value:'Çalışan bağlı AI sağlayıcısı kullanıldı'}]}:null;}
function withTiming(p,s){p.trace=[...(Array.isArray(p.trace)?p.trace:[]),{kind:'timing',label:'JARVIS yanıt süresi',value:`${Date.now()-s} ms`}];return p;}
async function simpleChat(core,req,env,ctx,text){const started=Date.now(),conversationContext=await conversation(core,req,env,ctx).catch(()=>''),expertPromise=getExperts(env,text,conversationContext).catch(()=>({kind:taskKind(text),picks:[],answers:[]})),aiPromise=workersAiFallback(env,text,conversationContext),response=await settleWithin(core.fetch(req.clone(),env,ctx),LIMITS.simpleCoreMs,null);if(response?.ok){let p;try{p=await response.clone().json();}catch{return response;}const experts=await settleWithin(expertPromise,LIMITS.expertMs+100,{answers:[]});const clean=cleanReply(experts?.answers?.[0]?.text||p.reply||'');if(clean)p.reply=clean;p.provider='JARVIS';return jsonResponse(withTiming(p,started),response.status);}const experts=await settleWithin(expertPromise,LIMITS.expertMs+100,{answers:[]}),expert=expertFallback(text,experts);if(expert)return jsonResponse(withTiming(expert,started));const ai=await settleWithin(aiPromise,LIMITS.fallbackAiMs+100,null);if(ai)return jsonResponse(withTiming(ai,started));return jsonResponse(withTiming(safeFallbackPayload(text,'JARVIS şu an yanıt üretemedi. Mesajın kaydedildi.','Tüm yanıt yolları başarısız'),started));}
async function orchestratedChat(core,req,env,ctx,text){const started=Date.now();const [base,webRows,toolRows,historyContext]=await Promise.all([settleWithin(core.fetch(req.clone(),env,ctx),LIMITS.complexCoreMs,null),wantsResearch(text)?research(core,req,env,ctx,text).catch(()=>[]):Promise.resolve([]),wantsTools(text)?tools(core,req,env,ctx,text).catch(()=>[]):Promise.resolve([]),conversation(core,req,env,ctx).catch(()=>'')]);const webContext=researchContext(webRows),conversationContext=[historyContext,webContext].filter(Boolean).join('\n\n');const experts=await getExperts(env,text,conversationContext).catch(()=>({kind:taskKind(text),picks:[],answers:[]}));const expert=expertFallback(text,experts);if(expert)return jsonResponse(withTiming(expert,started));const ai=await workersAiFallback(env,text,conversationContext);if(ai)return jsonResponse(withTiming(ai,started));if(base?.ok){let p;try{p=await base.clone().json();}catch{return base;}const clean=cleanReply(p.reply||'');if(clean&&!/^AI sağlayıcısı cevap veremedi/i.test(clean)){p.reply=clean;p.provider='JARVIS';return jsonResponse(withTiming(p,started),base.status);}}return jsonResponse(withTiming(safeFallbackPayload(text,'JARVIS şu an yanıt üretemedi. Mesajın kaydedildi.','Temiz sentezlenmiş yanıt üretilemedi'),started));}
export function createChatOrchestrator(core){if(!core?.fetch)throw new Error('CHAT_CORE_FETCH_REQUIRED');return async function handleChat(req,env,ctx){let text='';try{text=String((await req.clone().json())?.text||'').trim();}catch{}if(!text)return core.fetch(req,env,ctx);return needsOrchestration(text)?orchestratedChat(core,req,env,ctx,text):simpleChat(core,req,env,ctx,text);};}
