import core from './worker.js';

const HF_API='https://api.higgsfield.ai';
const HF_OPENAPI='https://docs.higgsfield.ai/docs/openapi.json';
const HF_DOCS='https://docs.higgsfield.ai/docs';
const HF_CLOUD='https://cloud.higgsfield.ai';
const HF_CAPS=['video-generation','reels-video','image-to-video','text-to-video'];
let hfSpecCache={ts:0,spec:null};

const te=new TextEncoder(),td=new TextDecoder();
const now=()=>Date.now(),uid=()=>crypto.randomUUID();
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const q1=(env,sql,...bind)=>env.DB.prepare(sql).bind(...bind).first();
const qall=async(env,sql,...bind)=>(await env.DB.prepare(sql).bind(...bind).all()).results||[];
const run=(env,sql,...bind)=>env.DB.prepare(sql).bind(...bind).run();
function cookies(req){return Object.fromEntries((req.headers.get('cookie')||'').split(';').filter(Boolean).map(x=>{const [k,...v]=x.trim().split('=');return[k,decodeURIComponent(v.join('='))]}))}
async function hmac(secret,data){const k=await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign('HMAC',k,te.encode(data))))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function authed(req,env){try{const t=cookies(req).jarvis_session,[b,s]=String(t||'').split('.');if(!b||!s||await hmac(env.JARVIS_SECRET||'CHANGE_ME',b)!==s)return false;const p=JSON.parse(atob(b.replaceAll('-','+').replaceAll('_','/')));return p.exp>now()}catch{return false}}
function b64u(bytes){return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function fromB64u(s){s=String(s).replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function masterKey(env){const raw=String(env.CREDENTIAL_MASTER_KEY||'').trim();if(raw.length<24)throw Error('CREDENTIAL_MASTER_KEY_NOT_SET');let b=null;try{const x=Uint8Array.from(atob(raw.replace(/\s+/g,'')),c=>c.charCodeAt(0));if([16,24,32].includes(x.length))b=x}catch{}if(!b)b=new Uint8Array(await crypto.subtle.digest('SHA-256',te.encode(raw)));return crypto.subtle.importKey('raw',b,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function enc(env,v){const iv=crypto.getRandomValues(new Uint8Array(12)),k=await masterKey(env),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,te.encode(String(v))));return b64u(iv)+'.'+b64u(ct)}
async function dec(env,v){const [a,b]=String(v||'').split('.');if(!a||!b)throw Error('INVALID_CREDENTIAL_BLOB');const k=await masterKey(env),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64u(a)},k,fromB64u(b));return td.decode(pt)}
async function body(req){try{return await req.json()}catch{return{}}}
function normalizeCap(x){x=String(x||'').toLowerCase().trim();if(x==='video'||x==='video-generation'||x==='reels'||x==='reel'||x==='reels-video')return x.startsWith('reel')?'reels-video':'video-generation';if(x==='image-to-video'||x==='img2video'||x==='i2v')return'image-to-video';if(x==='text-to-video'||x==='txt2video'||x==='t2v')return'text-to-video';return x}
function hfRegistry(){return {id:'higgsfield',name:'Higgsfield',base_url:HF_API,cloud_url:HF_CLOUD,docs_url:HF_DOCS,auth:{type:'api_key_pair',header:'Authorization: Key <KEY_ID>:<KEY_SECRET>'},capabilities:HF_CAPS,endpoint_source:HF_OPENAPI,endpoint_policy:'Only endpoints present in the official Higgsfield OpenAPI document are routable.'}}
async function hfSpec(){if(hfSpecCache.spec&&now()-hfSpecCache.ts<15*60*1000)return hfSpecCache.spec;const r=await fetch(HF_OPENAPI,{headers:{accept:'application/json'}});if(!r.ok)throw Error('HIGGSFIELD_OPENAPI_'+r.status);const spec=await r.json();hfSpecCache={ts:now(),spec};return spec}
function resolveRef(spec,node,seen=new Set()){if(!node||typeof node!=='object')return node;if(node.$ref&&String(node.$ref).startsWith('#/')){if(seen.has(node.$ref))return{};seen.add(node.$ref);let cur=spec;for(const p of node.$ref.slice(2).split('/'))cur=cur?.[p.replaceAll('~1','/').replaceAll('~0','~')];return resolveRef(spec,cur,seen)}if(Array.isArray(node))return node.map(x=>resolveRef(spec,x,new Set(seen)));const out={};for(const [k,v] of Object.entries(node))out[k]=resolveRef(spec,v,new Set(seen));return out}
function operationSchema(spec,op){const rb=op?.requestBody?.content||{};const schema=rb['application/json']?.schema||Object.values(rb)[0]?.schema||{};return resolveRef(spec,schema)}
function classifyOperation(spec,path,op){const schema=operationSchema(spec,op),schemaText=JSON.stringify(schema).toLowerCase(),text=[path,op?.operationId,op?.summary,op?.description,...(op?.tags||[])].filter(Boolean).join(' ').toLowerCase();const caps=[];const video=/video|motion|animate|animation|camera/.test(text)||/video/.test(schemaText);const image=/image|photo|portrait|soul/.test(text)||/image/.test(schemaText);if(video){caps.push('video-generation','reels-video');if(/image/.test(schemaText))caps.push('image-to-video');if(/prompt|text/.test(schemaText))caps.push('text-to-video')}if(image&&!video)caps.push('image-generation');return [...new Set(caps)]}
async function hfEndpoints(){const spec=await hfSpec(),out=[];for(const [path,item] of Object.entries(spec.paths||{})){const op=item?.post;if(!op||path.startsWith('/requests/'))continue;const caps=classifyOperation(spec,path,op);if(!caps.length)continue;out.push({path,url:HF_API+path,operationId:op.operationId||null,summary:op.summary||null,tags:op.tags||[],capabilities:caps})}return out}
async function hfCredential(env,cap=null){let rows=await qall(env,"SELECT * FROM credentials WHERE provider='higgsfield' AND enabled=1 ORDER BY priority ASC,created_at ASC");if(cap)rows=rows.filter(r=>{try{const c=JSON.parse(r.capabilities||'[]');return c.includes(cap)||c.includes('video-generation')}catch{return false}});if(!rows.length)return null;const r=rows[0],pair=JSON.parse(await dec(env,r.encrypted_secret));return {...r,keyId:pair.keyId,keySecret:pair.keySecret}}
function hfHeaders(c){return {'Authorization':`Key ${c.keyId}:${c.keySecret}`,'Content-Type':'application/json','Accept':'application/json'}}
async function saveHfCredential(env,b){let keyId=String(b.keyId||'').trim(),keySecret=String(b.keySecret||'').trim();if((!keyId||!keySecret)&&b.secret){const s=String(b.secret).trim(),i=s.indexOf(':');if(i>0){keyId=s.slice(0,i).trim();keySecret=s.slice(i+1).trim()}}if(!keyId||!keySecret)return json({error:'HIGGSFIELD_KEY_ID_AND_SECRET_REQUIRED',detail:'Use the Higgsfield Cloud API key ID and secret.'},400);const t=now(),cid=uid(),encrypted=await enc(env,JSON.stringify({keyId,keySecret})),caps=Array.isArray(b.capabilities)&&b.capabilities.length?b.capabilities.map(normalizeCap):HF_CAPS;await run(env,'INSERT INTO credentials(id,provider,label,kind,encrypted_secret,capabilities,endpoint,model,priority,enabled,meta,last_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',cid,'higgsfield',String(b.label||'Higgsfield').trim()||'Higgsfield','api_key_pair',encrypted,JSON.stringify(caps),HF_API,null,Number(b.priority||25),1,JSON.stringify({docs:HF_DOCS,cloud:HF_CLOUD,openapi:HF_OPENAPI,auth:'Authorization: Key <KEY_ID>:<KEY_SECRET>'}),'untested',t,t);return json({ok:true,id:cid,provider:'higgsfield',capabilities:caps})}
async function testHf(env,c){try{const probe='00000000-0000-0000-0000-000000000000',r=await fetch(`${HF_API}/requests/${probe}/status`,{headers:hfHeaders(c)});if(r.status===401)throw Error('HIGGSFIELD_INVALID_CREDENTIALS');if(r.status>=500)throw Error('HIGGSFIELD_API_'+r.status);await run(env,'UPDATE credentials SET last_status=?,last_error=NULL,last_test_at=?,updated_at=? WHERE id=?','ok',now(),now(),c.id);return {ok:true,status:r.status,detail:'Higgsfield Authorization header accepted; probe request is intentionally nonexistent.'}}catch(e){await run(env,'UPDATE credentials SET last_status=?,last_error=?,last_test_at=?,updated_at=? WHERE id=?','error',e.message,now(),now(),c.id);return {ok:false,error:e.message}}
async function routeHf(env,cap){cap=normalizeCap(cap);if(!HF_CAPS.includes(cap))throw Error('HIGGSFIELD_CAPABILITY_UNSUPPORTED');const credential=await hfCredential(env,cap);const endpoints=(await hfEndpoints()).filter(x=>x.capabilities.includes(cap));return {provider:'higgsfield',capability:cap,credential:credential?{id:credential.id,label:credential.label,status:credential.last_status}:null,selected:endpoints[0]||null,candidates:endpoints,registry:hfRegistry()}}
async function generateHf(env,b){const cap=normalizeCap(b.capability||'video-generation'),route=await routeHf(env,cap);if(!route.credential)throw Error('HIGGSFIELD_CREDENTIAL_REQUIRED');const c=await hfCredential(env,cap);let ep=route.selected;if(b.endpoint){const wanted=String(b.endpoint).trim();ep=route.candidates.find(x=>x.path===wanted||x.url===wanted);if(!ep)throw Error('HIGGSFIELD_ENDPOINT_NOT_IN_OFFICIAL_OPENAPI')}if(!ep)throw Error('HIGGSFIELD_NO_OFFICIAL_ENDPOINT_FOR_CAPABILITY');const payload=b.input&&typeof b.input==='object'?b.input:{};const r=await fetch(ep.url,{method:'POST',headers:hfHeaders(c),body:JSON.stringify(payload)}),text=await r.text();let out;try{out=JSON.parse(text)}catch{out={raw:text}}if(!r.ok)throw Error(`HIGGSFIELD_${r.status}:${String(out?.detail||out?.error||text).slice(0,300)}`);return {ok:true,provider:'higgsfield',capability:cap,endpoint:ep.path,...out}}
async function hfRequest(env,id,method='GET'){const c=await hfCredential(env);if(!c)throw Error('HIGGSFIELD_CREDENTIAL_REQUIRED');const suffix=method==='POST'?'cancel':'status',r=await fetch(`${HF_API}/requests/${encodeURIComponent(id)}/${suffix}`,{method,headers:hfHeaders(c)});if(method==='POST'&&r.status===204)return {ok:true,canceled:true};const text=await r.text();let out;try{out=JSON.parse(text)}catch{out={raw:text}}if(!r.ok)throw Error(`HIGGSFIELD_${r.status}:${String(out?.detail||out?.error||text).slice(0,300)}`);return out}
async function mergeScout(req,env,cap){const base=await core.fetch(req,env);let x={results:[]};try{x=await base.clone().json()}catch{}let route=null;try{route=await routeHf(env,cap)}catch{}const official={title:'Higgsfield — Official API',url:HF_DOCS,snippet:`Official Higgsfield provider • ${cap} • ${route?.candidates?.length||0} matching model endpoint(s) discovered from the official OpenAPI specification.`,provider:'higgsfield',official:true,capability:cap};return json({capability:cap,results:[official,...(x.results||[]).filter(r=>!String(r.url||'').includes('higgsfield.ai'))],route})}

async function hfRouter(req,env){const u=new URL(req.url),p=u.pathname,m=req.method;
 if(p==='/api/providers/higgsfield'&&m==='GET')return json(hfRegistry());
 if(p==='/api/higgsfield/openapi/endpoints'&&m==='GET')return json({provider:'higgsfield',source:HF_OPENAPI,endpoints:await hfEndpoints()});
 if(p==='/api/higgsfield/setup'&&m==='POST')return saveHfCredential(env,await body(req));
 if(p==='/api/credentials'&&m==='POST'){const clone=req.clone(),b=await body(clone);if(String(b.provider||'').toLowerCase()==='higgsfield')return saveHfCredential(env,b);return null}
 let mm=p.match(/^\/api\/credentials\/([^/]+)\/test$/);if(mm&&m==='POST'){const row=await q1(env,'SELECT * FROM credentials WHERE id=?',mm[1]);if(row&&String(row.provider).toLowerCase()==='higgsfield'){const pair=JSON.parse(await dec(env,row.encrypted_secret));return json(await testHf(env,{...row,...pair}))}return null}
 if(p==='/api/capabilities/route'&&m==='GET'&&String(u.searchParams.get('provider')||'higgsfield').toLowerCase()==='higgsfield')return json(await routeHf(env,u.searchParams.get('capability')||'video-generation'));
 if(p==='/api/higgsfield/generate'&&m==='POST')return json(await generateHf(env,await body(req)));
 mm=p.match(/^\/api\/higgsfield\/requests\/([^/]+)$/);if(mm&&m==='GET')return json(await hfRequest(env,mm[1],'GET'));
 mm=p.match(/^\/api\/higgsfield\/requests\/([^/]+)\/cancel$/);if(mm&&m==='POST')return json(await hfRequest(env,mm[1],'POST'));
 if(p==='/api/tools/discover'&&m==='GET'){const cap=normalizeCap(u.searchParams.get('capability')||'');if(HF_CAPS.includes(cap))return mergeScout(req,env,cap)}
 return null;
}

export default {
 async fetch(req,env,ctx){try{const u=new URL(req.url);if(u.pathname.startsWith('/api/')){if(!env.DB)return core.fetch(req,env,ctx);const candidate=/^\/api\/(providers\/higgsfield|higgsfield|capabilities\/route|tools\/discover|credentials)/.test(u.pathname);if(candidate){if(!(await authed(req,env))&&!u.pathname.startsWith('/api/providers/higgsfield'))return core.fetch(req,env,ctx);const r=await hfRouter(req,env);if(r)return r}}return core.fetch(req,env,ctx)}catch(e){return json({error:'HIGGSFIELD_INTEGRATION_ERROR',detail:e.message},500)}},
 async scheduled(event,env,ctx){if(core.scheduled)return core.scheduled(event,env,ctx)}
};
